# Generated by Django 5.0.7 on 2024-09-21 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0001_initial'),
        ('Trip', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripaction',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trip.trip'),
        ),
        migrations.AddField(
            model_name='logisticuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='logisticuser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='logisticuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='logisticuser_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='tripaction',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivercreditsum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
