# Generated by Django 5.0.7 on 2024-09-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
