# Generated by Django 5.0.7 on 2024-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=100)),
                ('v_number', models.CharField(max_length=15)),
                ('c_number', models.EmailField(max_length=100)),
                ('v_photo', models.ImageField(upload_to='driver_photos/')),
            ],
        ),
    ]
