# Generated by Django 5.0.7 on 2024-09-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0002_trip_after_load_kg_trip_before_load_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fuel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
