# Generated by Django 5.0.7 on 2024-09-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0003_alter_trip_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
